from rest_framework import routers
from .views import *

router = routers.DefaultRouter()
router.register('api/cows', CowsViewSet, 'cows')
router.register('api/semen_records', SemenRecordsViewSet , 'semen_records')
router.register('api/daily_feeding', DailyFeedingViewSet, 'daily_feeding')
router.register('api/cow_body_traits', CowBodyTraitsViewSet, 'cow_body_traits')
router.register('api/milk_targets', MilkTargetsViewSet, 'milk_targets')
router.register('api/milk_production', MilkProductionsViewSet, 'milk_production')
router.register('api/clients', ClientsViewSet, 'clients')
router.register('api/consumers', ConsumersViewSet, 'consumers')
router.register('api/milk_sales', MilkSalesViewSet, 'milk_sales')
router.register('api/milk_consumption', MilkConsumptionsViewSet, 'milk_consumption')
router.register('api/cow_weight_records', WeightRecordsViewSet, 'cow_weight_records')
router.register('api/cow_sales', CowSalesViewSet, 'cow_sales')
router.register('api/cow_treatments', TreatmentRecordsViewSet, 'cow_treatments')
router.register('api/cow_deworming', DewormingViewSet, 'cow_deworming')
router.register('api/cow_vaccinations', VaccinationsViewSet, 'cow_vaccinations')
router.register('api/cow_diseases', DiseasesViewSet, 'cow_diseases')
router.register('api/cow_deaths', DeathsViewSet, 'cow_deaths')
router.register('api/milk_sales_payments', MilkSalesPaymentsViewSet, 'milk_sales_payments')
router.register('api/ai_records', AiRecordsViewSet, 'ai_records')
router.register('api/calvings', CalvingsViewSet, 'calvings')
router.register('api/abortions_miscarriages', AbortionMiscarriagesViewSet, 'abortions_miscarriages')
router.register('api/employees', EmployeesViewSet, 'employees')
router.register('api/salary_advances', SalaryAdvancesViewSet, 'salary_advances')
router.register('api/employee_salaries', EmployeeSalariesViewSet, 'employee_salaries')
router.register('api/calf_feeding', CalfFeedingViewSet, 'calf_feeding')
router.register('api/feed_items', FeedItemsViewSet, 'feed_items')
router.register('api/cow_insurance', CowInsuranceViewSet, 'cow_insurance')
router.register('api/expenses', ExpenseViewSet, 'expenses')
router.register('api/incomes', IncomeViewSet, 'incomes')
urlpatterns = router.urls