# Generated by Django 2.2 on 2019-08-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='MilkSales',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('date', models.DateField(db_column='date', db_index=True)),
        #         ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        #         ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
        #         ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitaldairy.Clients')),
        #     ],
        #     options={
        #         'db_table': 'milk_sales',
        #         'unique_together': {('date', 'client')},
        #         'index_together': {('date', 'client')},
        #     },
        # ),
    ]
