# Generated by Django 2.2 on 2019-08-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MilkSales',
        ),
        migrations.DeleteModel(
            name='MilkConsumptions',
        ),
        # migrations.DeleteModel(
        #     name='MilkSales',
        # ),
        migrations.DeleteModel(
            name='MilkSalesPayments',
        ),
    ]
