# Generated by Django 2.2 on 2019-08-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0003_auto_20190815_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSalesPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('date_of_payment', models.DateField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitaldairy.Clients')),
            ],
            options={
                'db_table': 'milk_sales_payments',
            },
        ),
        migrations.CreateModel(
            name='MilkSales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitaldairy.Clients')),
            ],
            options={
                'db_table': 'milk_sales',
                'unique_together': {('date', 'client')},
                'index_together': {('date', 'client')},
            },
        ),
        migrations.CreateModel(
            name='MilkConsumptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date', db_index=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitaldairy.Consumers')),
            ],
            options={
                'db_table': 'milk_consumption',
                'unique_together': {('date', 'consumer')},
                'index_together': {('date', 'consumer')},
            },
        ),
    ]
