# Generated by Django 2.2 on 2019-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0005_auto_20190826_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=30),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
