# Generated by Django 2.2 on 2019-08-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0007_auto_20190829_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfeeding',
            name='feed_formulation',
        ),
        migrations.RemoveField(
            model_name='feedformulation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='feedingprogramme',
            name='quantity',
        ),
        migrations.AddField(
            model_name='dailyfeeding',
            name='feed_item',
            field=models.ForeignKey(default=[0, 1, 2, 3, 4, 5, 6], on_delete=django.db.models.deletion.CASCADE, to='digitaldairy.FeedItems'),
            preserve_default=False,
        ),
    ]
