# Generated by Django 2.2 on 2019-09-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0009_auto_20190910_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salaryadvances',
            table='employees_salary_advances',
        ),
    ]
