# Generated by Django 3.1 on 2020-08-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaldairy', '0010_auto_20190910_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecords',
            name='semen_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitaldairy.semenrecords'),
        ),
    ]
