# Generated by Django 2.2 on 2019-09-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'events_clients',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('venue_color', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('invoice_date', models.DateField()),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_management.Deliveries')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='StandardQuotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'standard_quotations',
            },
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_date', models.DateField()),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.Invoices')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=100)),
                ('venue_color', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('quote_date', models.DateField()),
                ('total_quotation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.Clients')),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
        migrations.CreateModel(
            name='QuotationParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_management.Deliveries')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.Items')),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_management.Quotations')),
                ('standard_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_management.StandardQuotations')),
            ],
            options={
                'db_table': 'quotation_parts',
            },
        ),
        migrations.AddField(
            model_name='deliveries',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_management.Quotations'),
        ),
    ]
