from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="home"),
    path('digitaldairy/', views.index, name="digital_dairy"),
    path('send_message', views.send_message, name="send_message"),
    path('cows/', views.cows, name="cows"),
    path('body_traits/', views.cow_profile, name="cow_profile"),
    path('daily_milk_production/', views.daily_milk_production,
         name="daily_milk_production"),
    path('milk_sales/', views.milk_sales, name="milk_sales"),
    path('milk_sales_payments/', views.milk_sales_payments, name="milk_sales_payments"),
    path('monthly_milk_production/', views.monthly_milk_production,
         name="monthly_milk_production"),
    path('clients_consumers/', views.get_clients_and_consumers,
         name="clients_consumers"),
    path('clients_statements/', views.clients_statements,
         name="clients_statements"),
    path('consumers_statements/', views.consumers_statements,
         name="consumers_statements"),
    path('employees/', views.get_employees, name="employees"),
    path('cow_insurance/', views.cow_insurance, name="cow_insurance"),
    path('income/', views.income, name="income"),
    path('expenses/', views.expenses, name="expenses"),
    path('milk_production_history/',
         views.cow_milk_production_history, name="milk_production_history"),
    path('milk_production_statistics/',
         views.get_milk_production_statistics, name="milk_production_statistics"),
    path('cow_sales/', views.get_cow_sales, name="cow_sales"),
    path('weight_recording/', views.get_weight_recording, name="weight_recording"),
    path('calf-management/', views.calf_management, name="calf_management"),
    path('cow_health/', views.get_cow_health, name="cow_health"),
    path('cow_feeds/', views.cow_feeds, name="cow_feeds"),
    path('cow_feed_items/', views.cow_feed_items, name="cow_feed_items"),
    path('daily_feeding/', views.daily_feeding, name="daily_feeding"),
    path('deworming/', views.get_deworming, name="deworming"),
    path('vaccinations/', views.get_vaccinations, name="vaccinations"),
    path('deaths_autopsy/', views.get_deaths_autopsy, name="deaths_autopsy"),
    path('cow_diseases/', views.cow_diseases, name="cow_diseases"),
    path('semen_catalog/', views.get_semen_catalog, name="semen_catalog"),
    path('ai-records/', views.get_ai_records, name="ai_records"),
    path('pregnancy-diagnosis/', views.get_pregnancy_diagnosis,
         name="pregnancy_diagnosis"),
    path('calving_maternity/', views.calving_maternity, name="calving_maternity"),
    path('abortions_miscarriages/', views.abortions_miscarriages,
         name="abortions_miscarriages"),
    path('breeding-alerts/', views.breeding_alerts, name="breeding_alerts"),
    path('breeding-statistics/', views.breeding_statistics,
         name="breeding_statistics"),
    path('client_purchase_history/<str:client_id>/', views.get_client_purchase_history,
         name="client_purchase_history"),
    path('consumer_consumption_history/<str:consumer_id>/', views.get_consumer_consumption_history,
         name="consumer_consumption_history"),
    path('milk_sales_statistics/', views.get_sales_statistics,
         name="milk_sales_statistics"),
    path('save_cow', views.save_cow, name="save_cow"),
    path('save_calf', views.save_calf, name="save_calf"),
    path('save_weight', views.save_weight, name="save_weight"),
    path('save_milk_production', views.save_milk_production,
         name="save_milk_production"),
    path('save_daily_milk_target', views.save_daily_milk_target,
         name="save_daily_milk_target"),
    path('save_client', views.save_client, name="save_client"),
    path('save_milk_sale', views.save_milk_sale, name="save_milk_sale"),
    path('save_treatment_record', views.save_cow_treatment_record,
         name="save_treatment_record"),
    path('save_deworming_record', views.save_cow_deworming_record,
         name="save_deworming_record"),
    path('save_cow_disease_record', views.save_cow_disease_record,
         name="save_cow_disease_record"),
    path('save_cow_death_record', views.save_cow_death_record,
         name="save_cow_death_record"),
    path('save_semen_catalog', views.save_semen_catalog, name="save_semen_catalog"),
    path('save_cow_autopsy_record', views.save_cow_autopsy_record,
         name="save_cow_autopsy_record"),
    path('save_cow_ai_record', views.save_cow_ai_record, name="save_cow_ai_record"),
    path('save_pregnancy_calendar', views.save_pregnancy_calendar,
         name="save_pregnancy_calendar"),
    path('save_calving_record', views.save_calving_record,
         name="save_calving_record"),
    path('save_abortion_miscarriage_record', views.save_abortion_miscarriage_record,
         name="save_abortion_miscarriage_record"),
    path('save_pregnancy_diagnosis', views.save_pregnancy_diagnosis,
         name="save_pregnancy_diagnosis"),
    path('save_cow_vaccination_record', views.save_cow_vaccination_record,
         name="save_cow_vaccination_record"),
    path('save-cow-sale', views.save_cow_sale, name="save_cow_sale"),
    path('save_feed_item', views.save_feed_item, name="save_feed_item"),
    # modify to decrease remaining quantity when daily feeding is saved
    path('save_daily_feeding', views.save_daily_feeding, name="save_daily_feeding"),
    path('save_feed_formulation', views.save_feed_formulation,
         name="save_feed_formulation"),
    path('save_feed_formulation_part', views.save_feed_formulation_part,
         name="save_feed_formulation_part"),
    path('save_milk_consumption', views.save_milk_consumption,
         name="save_milk_consumption"),
    path('save_consumer', views.save_consumer, name="save_consumer"),
    path('save_income', views.save_income, name="save_income"),
    path('save_expense', views.save_expense, name="save_expense"),
    path('delete_cow', views.delete_cow, name="delete_cow"),
    path('delete_cow_body_traits', views.delete_cow_body_traits,
         name="delete_cow_body_traits"),
    path('delete_milk_production', views.delete_day_milk_production,
         name="delete_milk_production"),
    path('delete_client', views.delete_client, name="delete_client"),
    path('delete_client', views.delete_client, name="delete_client"),
    path('delete_cow_death', views.delete_cow_death, name="delete_cow_death"),
    path('delete_cow_death_autopsy', views.delete_cow_death_autopsy, name="delete_cow_death_autopsy"),
    path('delete_cow_sale', views.delete_cow_sale, name="delete_cow_sale"),
    path('delete_consumer', views.delete_consumer, name="delete_consumer"),
    path('delete_employee', views.delete_employee, name="delete_employee"),
    path('delete_milk_consumption', views.delete_milk_consumption,
         name="delete_milk_consumption"),
    path('delete_milk_sale', views.delete_milk_sale, name="delete_milk_sale"),
    path('delete_milk_sale_payment', views.delete_milk_sale_payment, name="delete_milk_sale_payment"),
    path('delete_expense', views.delete_expense, name="delete_expense"),
    path('delete_income', views.delete_income, name="delete_income"),
    path('delete_semen_catalog', views.delete_semen_catalog, name="delete_semen_catalog"),
    path('delete_cow_disease', views.delete_cow_disease, name="delete_cow_disease"),
    path('delete_vaccination', views.delete_vaccination, name="delete_vaccination"),
    path('delete_de_worming', views.delete_deworming, name="delete_de_worming"),
    path('delete_treatment', views.delete_treatment, name="delete_treatment"),
    path('delete_weight', views.delete_weight, name="delete_weight"),
    path('delete_feed_item', views.delete_feed_item, name="delete_feed_item"),
    path('delete_feed_formulation', views.delete_feed_formulation,
         name="delete_feed_formulation"),
    path('delete_daily_feeding', views.delete_daily_feeding,
         name="delete_daily_feeding"),
    path('delete_feeding_programme', views.delete_feeding_programme,
         name="delete_feeding_programme"),
    path('delete_feed_formulation_part', views.delete_feed_formulation_part,
         name="delete_feed_formulation_part"),
    path('delete_pregnancy_diagnosis', views.delete_pregnancy_diagnosis,
         name="delete_pregnancy_diagnosis"),
    path('delete_ai_record', views.delete_ai_record, name="delete_ai_record"),
    path('delete_calving', views.delete_calving, name="delete_calving"),
    path('delete_milk_production_target', views.delete_milk_production_target,
         name="delete_milk_production_target"),
    path('delete_calf_feeding', views.delete_calf_feeding,
         name="delete_calf_feeding"),
    path('delete_cow_insurance', views.delete_cow_insurance,
         name="delete_cow_insurance"),
]

app_name = 'digitaldairy'
